[package]
name = "gw-generator"
version = "0.1.0"
authors = ["Nervos Network"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gw-types = { path = "../types" }
gw-common = { path = "../common" }
gw-store = { path = "../store" }
anyhow = "1.0"
blake2b-rs = "0.2"
ckb-vm = { git = "https://github.com/nervosnetwork/ckb-vm.git", tag = "0.19.1", features = ["detect-asm"] }
thiserror = "1.0"
lazy_static = "1.4"
secp256k1 = { version = "0.20", features = ["recovery"] }
sha3 = "0.9.1"

[dev-dependencies]
hex = "0.4.2"
ckb-script = "0.37.0"
ckb-types = "0.37.0"
ckb-error = "0.37.0"
ckb-crypto = "0.37.0"
ckb-hash = "0.37.0"
ckb-traits = "0.37.0"
ckb-fixed-hash = "0.37.0"
rand = "0.8"
